# Generated by Django 3.1.12 on 2024-12-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('republished', 'Republished')], default='draft', max_length=11),
        ),
    ]
